REM Export without the non-required External Id Lookups
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Default__c                                                                                                                                                                                                                                     FROM agentforce1__Schema_Instruction__c"                                --result-format "csv" --output-file "../config-data/no-lookups/000_agentforce1__Schema_Instruction__c.csv"         --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Latest__c, agentforce1__Prompt_Output_Hash__c, agentforce1__Prompt_Output_Length__c, agentforce1__Prompt_Output__c, agentforce1__Version_Number__c, agentforce1__Schema_Instruction__r.agentforce1__External_Id__c                                   FROM agentforce1__Schema_Instruction_Version__c"                        --result-format "csv" --output-file "../config-data/no-lookups/001_agentforce1__Schema_Instruction_Version__c.csv" --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Order__c, agentforce1__Hierarchy_Changed__c, agentforce1__Schema_Changed__c, agentforce1__Instruction__c, agentforce1__Purpose_Description__c, agentforce1__Schema_Instruction__r.agentforce1__External_Id__c                                                                                                                               FROM agentforce1__Schema_Mapping__c"                                    --result-format "csv" --output-file "../config-data/no-lookups/002_agentforce1__Schema_Mapping__c.csv"             --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Latest__c, agentforce1__Prompt_Output_Hash__c, agentforce1__Prompt_Output_Length__c, agentforce1__Prompt_Output__c, agentforce1__Version_Number__c, agentforce1__Schema_Mapping__r.agentforce1__External_Id__c                                       FROM agentforce1__Schema_Mapping_Version__c"                            --result-format "csv" --output-file "../config-data/no-lookups/003_agentforce1__Schema_Mapping_Version__c.csv"     --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Purpose_Description__c, agentforce1__Relationship_Field__c, agentforce1__Relationship_Name__c,agentforce1__Order__c,  agentforce1__Schema_Mapping__r.agentforce1__External_Id__c, agentforce1__sObjectType__c, agentforce1__Parent_sObjectType__c FROM agentforce1__Mapped_sObject__c ORDER BY agentforce1__Order__c"     --result-format "csv" --output-file "../config-data/no-lookups/004_agentforce1__Mapped_sObject__c.csv"             --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__JSON_Type__c, agentforce1__Length__c, agentforce1__Purpose_Description__c, agentforce1__Type__c, agentforce1__Mapped_sObject__r.agentforce1__External_Id__c                                                                                       FROM agentforce1__Mapped_sObject_Field__c"                              --result-format "csv" --output-file "../config-data/no-lookups/005_agentforce1__Mapped_sObject_Field__c.csv"       --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"


REM Export with all the External Id Lookups in place to link everything together, including  the self-lookups
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Default__c, agentforce1__Latest_Version__r.agentforce1__External_Id__c                                                                                                                                                                                                                                     FROM agentforce1__Schema_Instruction__c"                                --result-format "csv" --output-file "../config-data/000_agentforce1__Schema_Instruction__c.csv"                    --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Latest__c, agentforce1__Prompt_Output_Hash__c, agentforce1__Prompt_Output_Length__c, agentforce1__Prompt_Output__c, agentforce1__Version_Number__c, agentforce1__Schema_Instruction__r.agentforce1__External_Id__c                                                                                               FROM agentforce1__Schema_Instruction_Version__c"                        --result-format "csv" --output-file "../config-data/001_agentforce1__Schema_Instruction_Version__c.csv"            --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Order__c, agentforce1__Hierarchy_Changed__c, agentforce1__Schema_Changed__c, agentforce1__Instruction__c, agentforce1__Purpose_Description__c, agentforce1__Latest_Version__r.agentforce1__External_Id__c, agentforce1__Schema_Instruction__r.agentforce1__External_Id__c                                                                                                                               FROM agentforce1__Schema_Mapping__c"                                    --result-format "csv" --output-file "../config-data/002_agentforce1__Schema_Mapping__c.csv"                        --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Is_Latest__c, agentforce1__Prompt_Output_Hash__c, agentforce1__Prompt_Output_Length__c, agentforce1__Prompt_Output__c, agentforce1__Version_Number__c, agentforce1__Schema_Mapping__r.agentforce1__External_Id__c                                                                                                   FROM agentforce1__Schema_Mapping_Version__c"                            --result-format "csv" --output-file "../config-data/003_agentforce1__Schema_Mapping_Version__c.csv"                --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__Purpose_Description__c, agentforce1__Relationship_Field__c, agentforce1__Relationship_Name__c, agentforce1__Order__c, agentforce1__Parent_sObject__r.agentforce1__External_Id__c, agentforce1__Schema_Mapping__r.agentforce1__External_Id__c, agentforce1__sObjectType__c, agentforce1__Parent_sObjectType__c FROM agentforce1__Mapped_sObject__c ORDER BY agentforce1__Order__c"     --result-format "csv" --output-file "../config-data/004_agentforce1__Mapped_sObject__c.csv"                        --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
call sf data export bulk --query "SELECT Name, agentforce1__External_Id__c, agentforce1__Ignore_Triggers__c, agentforce1__JSON_Type__c, agentforce1__Length__c, agentforce1__Purpose_Description__c, agentforce1__Type__c, agentforce1__Mapped_sObject__r.agentforce1__External_Id__c                                                                                                                                                   FROM agentforce1__Mapped_sObject_Field__c"                              --result-format "csv" --output-file "../config-data/005_agentforce1__Mapped_sObject_Field__c.csv"                  --wait 60 --target-org "lightweightagentforcerecordbuilder" --line-ending "CRLF"
