REM NO LOOKUPS
call sf data upsert bulk --sobject "agentforce1__Schema_Instruction__c"         --file "../config-data/no-lookups/000_agentforce1__Schema_Instruction__c.csv"          --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Instruction_Version__c" --file "../config-data/no-lookups/001_agentforce1__Schema_Instruction_Version__c.csv"  --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Mapping__c"             --file "../config-data/no-lookups/002_agentforce1__Schema_Mapping__c.csv"              --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Mapping_Version__c"     --file "../config-data/no-lookups/003_agentforce1__Schema_Mapping_Version__c.csv"      --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Mapped_sObject__c"             --file "../config-data/no-lookups/004_agentforce1__Mapped_sObject__c.csv"              --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Mapped_sObject_Field__c"       --file "../config-data/no-lookups/005_agentforce1__Mapped_sObject_Field__c.csv"        --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"

REM WITH LOOKUPS TO FIX (SELF) LOOKUP FIELD
call sf data upsert bulk --sobject "agentforce1__Schema_Instruction__c"         --file "../config-data/000_agentforce1__Schema_Instruction__c.csv"          --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Instruction_Version__c" --file "../config-data/001_agentforce1__Schema_Instruction_Version__c.csv"  --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Mapping__c"             --file "../config-data/002_agentforce1__Schema_Mapping__c.csv"              --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Schema_Mapping_Version__c"     --file "../config-data/003_agentforce1__Schema_Mapping_Version__c.csv"      --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Mapped_sObject__c"             --file "../config-data/004_agentforce1__Mapped_sObject__c.csv"              --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
call sf data upsert bulk --sobject "agentforce1__Mapped_sObject_Field__c"       --file "../config-data/005_agentforce1__Mapped_sObject_Field__c.csv"        --external-id "agentforce1__External_Id__c" --wait 60 --target-org "TA-Demo-Jam" --line-ending "CRLF"
